### ISSUE TITLE
TLPC v213.f3z might be corrupted

### ISSUE THREAD

**Issue by regerohan** [volzotan/tlpic#1]
Hello,

Thanks for creating and making the project open-source. It looks like a fun camera!

However, the CAD file TLPC is not opening in Fusion 360.

![image](https://github.com/user-attachments/assets/44e3df46-193a-4154-ae52-86774a231ba0)

**Comment by volzotan** [comment]
Just checked and had no issue importing the f3z files with Fusion (newest version, on MacOS).
Import via File > Open (apparently conversion is performed "on the cloud", but once done it imported without error).
For your convenience I added STEP files to the repository, this should work without issues with Fusion and many other CAD software packages.
